### ISSUE TITLE
Minimal instruction how to use the application would be appreciated.

### ISSUE THREAD

**Issue by izikeros** [michalfapso/kdenlive_slideshow_editor#3]
This seems like piece of software I planned to write, but I'm not sure how to use it. Would be great if minimal instruction how to create slideshow would be added to README.

Is it required to create Kdenlive project first and then load images, adjust bounding boxes?
Is music added in Kdenlive project that is read in the beginning?

Thank you for sharing the project.

**Comment by michalfapso** [comment]
I planned to add some basic instructions after publishing the project. I'll try to do it this weekend.

**Comment by michalfapso** [comment]
Hi @izikeros, I've added installation and usage sections to the README.md file. I liked your installation approach using the `requirements.txt` file, I just didn't test it. If you can rewrite those current instructions to use the `requirements.txt` file, please just send me a pull request for it.

Please, also let me know if you are able to use the project now following the README.md. I'll add a video tutorial with a sample output soon.
